name: air_cli
description: The official CLI for the Air Framework. Streamline your Flutter development with modular architecture, automated code generation, and scalable state management.
version: 1.0.10
repository: https://github.com/AndreyDAraya/air-cli
environment:
  sdk: ^3.10.7

executables:
  air: air

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
